### ISSUE TITLE
Implement fancier test utilities and test fixtures

### ISSUE THREAD

**Issue by dancingbug** [fernandobatels/rsfbclient#59]
Create some common functionality for use by tests.

- generation of raw sql (maybe to be replaced later by query builder as discussed in #48)
- consider adding string formatting libraries to `dev-dependencies` like [this](https://crates.io/crates/indoc) or [this](https://crates.io/crates/const_format) for ease of generating nice statements
- well-documented connection setup/teardown routines, for example setting up multiple connections/transactions or creating/dropping tables with unique names to avoid transaction deadlocks in parallel tests
- move test database creation into separate scripts + config (docker/git action could still reference them) to make it easier for users to run tests locally with minimal dependencies,  and/or create some fixed .fdb files corresponding to different fb server configurations
- other ideas?

**Comment by fernandobatels** [comment]
I think there are two points more relevant here:

- Generation of unique name tables/resources/transactions to avoid deadlocks
   -  In some tests we already we a [static variable](https://github.com/fernandobatels/rsfbclient/blob/master/src/tests/charset.rs#L5) to solve this problem. Maybe we can create a standard approach for this.
- Environment reproduction.  
   - Maybe we can use some docker images with fb server. We can build a script for run in our local environment or in our github actions, starting the fb servers containers in different ports. With different ports, we can use the same ['test multiplexing' approach](https://github.com/fernandobatels/rsfbclient/blob/master/src/tests/mod.rs#L4), used today for run the all crate features, to run the tests in all this servers

**Comment by afsmi** [comment]
@jairinhohw @fernandobatels now that I have to fix tests for my changes in #75 I'm noticing some of the ways in which our current testing setup is not so flexible/scalable.

I'd like to change it and would like your feedback.

The main improvements I had in mind:
* make something more like our ci matrix for different configurations. Right now it's a bit like this, but it is only 1xn matrix ( the `for XYZ -> BuilderType` list) and there is no concept of `include`  where one can introduce extra config variables on a case-by-case basis
  * any suggestions on implementing this? I think I know how to do it with macros but it will be ugly. Maybe `const`/`const fn` could be helpful here?
* factor out the `cbuilder` set-up into separate inline modules or macros
* create an inline module somewhere whose only purpose is to re-export a common set of items to be included by all tests.
* replace hard-coded dyn lib/database file paths to use environment variables, but with default settings (or maybe cargo has a specific feature for these kinds of variables)
* move unit tests in `src/**/xyz.rs` into separate sub-modules like
  ```
    // in src/statement.rs //
    ...
    #[cfg(test)]
    mod statement_rs_tests {
      use super::*; // to import declarations in statement module
      use crate::common_test_imports::*;
      ...
    }
   ```


Also: is there a reason we use `src/tests/` instead of just `tests/` as recommended  by the [official cargo guide](https://doc.rust-lang.org/cargo/guide/tests.html) ?

**Comment by fernandobatels** [comment]
>     * move unit tests in source files into test-specific sub-modules like

I'm ok with this change. What you think @jairinhohw ?

> Also: is there a reason we use src/tests/ instead of just tests/ as recommended by the official cargo guide ?

Hmm, the `src/tests/` represents more an approach to deal with the 'multi features tests' that a integration test.

**Comment by fernandobatels** [comment]
> create an inline module somewhere whose only purpose is to re-export a common set of items to be included by all tests.

What items are you thinking about?

**Comment by fernandobatels** [comment]
> make something more like our ci matrix for different configurations.

Do you are thinking about the firebird versions?

**Comment by jairinhohw** [comment]
>     * make something more like our ci matrix for different configurations. Right now it's a bit like this, but it is only 1xn matrix ( the `for XYZ -> BuilderType` list) and there is no concept of `include`  where one can introduce extra config variables on a case-by-case basis
>       
>       * any suggestions on implementing this? I think I know how to do it with macros but it will be ugly. Maybe `const`/`const fn` could be helpful here?

I don't know exactly what kind of data you want to add, but you can use the `env!` macro to access environment variables at compile time.


>     * generally try to rely less on macros if possible

Macros are the only way i know of to create multiple versions of the same tests as is done (one test for every firebird client type).
Other than that it is good where possible to remove the macro usage.

>     * replace hard-coded dyn lib/database file paths by environment variables, but with default settings (or maybe cargo has a specific feature for these kinds of variables)

The hard coded settings are used only for tests, so i don't think it is a problem, however we can use the `env!` or `option_env` macro.

>     * move unit tests in source files into test-specific sub-modules like
>       ```
>       // in src/statement.rs //
>       ...
>       #[cfg(test)]
>       mod statement_rs_tests {
>         use super::*; // to import declarations in statement module
>         use crate::common_test_imports::*;
>       
>         mk_tests_default!{
>           ...
>       }
>       ```

I personally like to have some tests in the modules where the code the tests test lives, as the ones in the `stmt_cache` for example, but it is only a preference.
