### ISSUE TITLE
serde interoperability

### ISSUE THREAD

**Issue by dancingbug** [fernandobatels/rsfbclient#72]
It would be nice to be able to use existing serde-derives with `FromRow` or `IntoParams`

an example use case is converting between JSON/YAML/protobuf/etc and Firebird

**Comment by jairinhohw** [comment]
Do you mean using serde to serialize parameters / desserialize columns?
If that is the case, how should the user choose the format (JSON/YAML)?
Maybe add `Json` / `Yaml` / etc wrapper structs that can be used as parameter or in columns place.

**Comment by afsmi** [comment]
In serde, you say how to take a type you want to deserialize/serialize, and say how it translates into the 29 [types](https://serde.rs/data-model.html) of serde's data model. Once you do that you can derive translations to anything else that speaks serde using the specific crate functions. 

so in the case of your question it would just look like
```
let r = queryable.query(...)?;
let ser_result = serde_json::to_string(r)?;
...
```
in this example it would require to have `impl<T: FromRow> serde::ser::Serialize for T {...}` somewhere in core but's probably better to do `impl Serialize for Column {...}` instead in core somewhere. I think serde probably has a generic impl like `impl<T: Serialize> Serialize for Vec<T>` which means we really only have to implement `Serialize` for `ColumnType`/`Column` and then we get `Vec<Column>` automatically. see https://serde.rs/impl-serialize.html and https://serde.rs/derive.html .

Probably we can even use serde-derive on `ColumnType`  to do most of the work (maybe it will need a bit of help with `Binary` and `Timestamp` variants) I haven't tried this yet but it might be easy.

actually i think one could hypothetically then do the same for `XSQLVAR` format (but that would have to be more manual instead of using macros) to get automatic translation into `Vec<Column>`

**Comment by fernandobatels** [comment]
> so in the case of your question it would just look like
> 
> ```
> let r = queryable.query(...)?;
> let ser_result = serde_json::to_string(r)?;
> ...
> ```

This is a nice feature(serialize the query results). I can't see a valid example for input the params, but for serialized the query's results yes. 

I'm busy with the #48, but i can try implement this in the future.
