### ISSUE TITLE
Abstract SQL statement type

### ISSUE THREAD

**Issue by dancingbug** [fernandobatels/rsfbclient#78]
It could be helpful to introduce an abstract SQL statement type in the main crate.

By this i mean that instead of

`query_iter<...>(... sql: &str ...)`

we have instead something like

`query_iter<..., T: SqlStatement>(..., sql: T, ...)`

with a default impl for `&str`

`SqlStatement` here could be things like `NamedParamsStatement<'a>(&'a str)` or some future `StatementBuilder`

that way it becomes easier to extend functionality around SQL statements.

There might be other approaches besides using a trait in the above way.
Note that implementing this might be more complex than it appears.. it might have to touch a lot of methods in `Connection`, `Transaction`, and `Statement` to be fully flexible

**Comment by fernandobatels** [comment]
This is a nice point. 

But for now I can't realize how we can use a type like `NamedParamsStatement` restriction the params used. What is your idea for this?

**Comment by afsmi** [comment]
I'm not totally sure what you mean, I but I will make some additional comments, and maybe it will answer your question. 
i will be a bit loose with writing the types for simplification.

If these comments do not answer your question, could you clarify on what you mean?

1. I didn't say it directly, but trait `SqlStatement` would have a method like `SqlStatement::compile(&self)` or `convert(&self)` or something which is called by concrete methods of `Connection`, `Statement` and `Transaction` or the `XYZData` variants,  it allows to vary the pre-processing based on which implementation of `SqlStatement` is provided.

2. My thoughts for `NamedParamsStatement` were to use the wrapper to enable/disable parsing of the sql statement for named parameters, by doing [this](https://github.com/fernandobatels/rsfbclient/compare/fernandobatels:e0a7006...fernandobatels:154cd94#diff-fdbffa5e7a50bcc767fff75f5c23b30abacf30cebee409d37a9e8669510135ccR147) in the `SqlStatement::compile` implementation for `NamedParamsStatement` instead of branching using run-time arguments like `named_params:bool` in the link

Something else that comes to mind now- an interesting possibility with this is to have a different `prepare` implementation for `Transaction` which is generic in it's *return* types depending on the kind of `SqlStatement` you pass.
So instead of `Transaction::prepare(...) -> Result<Statement, FbError>` you have `Transaction::prepare_fancy<T:SqlStatement>(... sql: T ...) -> Result<<T as SqlStatement>::Prepared, FbError>`
which is different depending on `T`. 

As an example for `NamedParamsStatement`, `Prepared` could be `FnMut( &Transaction, Named ) -> Iterator<Item=...>` that you can just call directly with your parameter struct.
Maybe it's even possible using this method to validate the `:arg`s  in the query string against the struct type at the `prepare` stage instead of at the `query` stage, and then only allow the exact struct as the input to that `FnMut` (maybe no need to build an explicit `HashMap`, you can the same with the returned closure ).

**Comment by fernandobatels** [comment]
> If these comments do not answer your question, could you clarify on what you mean?

I understand your point now. Sorry for my poor explanation. I was worried about how you would handle the parameters for the queries. But the Diesel example solve this.

----

You have an example to the final api utilization?
